# Generated by Django 4.2.7 on 2024-06-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="progress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
